name: test
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: borales/actions-yarn@v3
        with:
          cmd: install

      - uses: borales/actions-yarn@v3
        with:
          cmd: build
