name: test
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update -y
          sudo apt install -y build-essential

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Build public/db.json
        run: yarn cli compute data -o public/db.json

      - name: Build site
        shell: bash
        run: yarn build
